import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Share } from 'react-native';
import type { CallRecord } from '../types';
import { formatTimestamp } from '../utils/format';

type Lang = 'es' | 'en';

const L = {
  es: {
    noSummary: 'No hay resumen disponible todavía.',
    notMentioned: 'No se mencionó.',
    noMeds: 'No se mencionaron medicinas.',
    noSummaryAvailable: 'No hay resumen disponible.',
    title: 'Resumen de visita médica',
    inShort: 'En pocas palabras:',
    meds: '💊 Medicinas',
    nextVisit: '📅 Próxima visita',
    doAtHome: '✅ Qué hacer en casa',
    whenToCall: '⚠️ Cuándo llamar al doctor',
    urgentTitle: '🚨 SEÑALES DE ALARMA',
    footer: 'Generado por MedLingua. Confirme información importante con su doctor.',
    dialogTitle: 'Enviar resumen a familia',
  },
  en: {
    noSummary: 'No summary available yet.',
    notMentioned: 'Not mentioned.',
    noMeds: 'No medications mentioned.',
    noSummaryAvailable: 'No summary available.',
    title: 'Doctor visit summary',
    inShort: 'In short:',
    meds: '💊 Medications',
    nextVisit: '📅 Next visit',
    doAtHome: '✅ What to do at home',
    whenToCall: '⚠️ When to call the doctor',
    urgentTitle: '🚨 WARNING SIGNS',
    footer: 'Generated by MedLingua. Always confirm important information with your doctor.',
    dialogTitle: 'Send summary to family',
  },
};

function bulletList(items: string[], emptyLabel: string) {
  return items.length ? items.map(item => `• ${item}`).join('\n') : `• ${emptyLabel}`;
}

export function buildSummaryText(call: CallRecord, lang: Lang = 'es'): string {
  const t = L[lang];
  const summary = call.summary;
  if (!summary) return t.noSummary;

  const medications = summary.medications.length
    ? summary.medications.map(m => `• ${m.name}: ${m.dose}`).join('\n')
    : `• ${t.noMeds}`;

  const urgentBlock = summary.urgentWarnings && summary.urgentWarnings.length > 0
    ? [
        '',
        t.urgentTitle,
        ...summary.urgentWarnings.map(w => `• ${w.title} → ${w.action}`),
      ]
    : [];

  return [
    t.title,
    formatTimestamp(call.startedAt, lang),
    ...urgentBlock,
    '',
    t.inShort,
    summary.rawText || summary.simpleExplanation || t.noSummaryAvailable,
    '',
    t.meds,
    medications,
    '',
    t.nextVisit,
    summary.nextVisit || summary.appointmentTime || t.notMentioned,
    '',
    t.doAtHome,
    bulletList(summary.homeInstructions?.length ? summary.homeInstructions : summary.followUpInstructions, t.notMentioned),
    '',
    t.whenToCall,
    bulletList(summary.whenToCallDoctor ?? [], t.notMentioned),
    '',
    t.footer,
  ].join('\n');
}

// Kept for backward compatibility
export const buildSpanishSummaryText = (call: CallRecord): string => buildSummaryText(call, 'es');

export async function shareCallSummary(call: CallRecord, lang: Lang = 'es'): Promise<void> {
  const t = L[lang];
  const text = buildSummaryText(call, lang);

  if (!(await Sharing.isAvailableAsync())) {
    await Share.share({ message: text });
    return;
  }

  const html = `
    <html>
      <body style="font-family: -apple-system, BlinkMacSystemFont, Helvetica, Arial, sans-serif; padding: 28px; color: #1A1B1F;">
        <div style="font-size: 13px; color: #0F5BA8; font-weight: 700;">MedLingua</div>
        <h1 style="font-size: 28px; margin: 6px 0 4px;">${t.title}</h1>
        <div style="font-size: 15px; color: #555960; margin-bottom: 24px;">${formatTimestamp(call.startedAt, lang)}</div>
        <pre style="white-space: pre-wrap; font-size: 18px; line-height: 1.45; font-family: inherit;">${text}</pre>
      </body>
    </html>
  `;
  const file = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(file.uri, {
    mimeType: 'application/pdf',
    dialogTitle: t.dialogTitle,
  });
}
